---
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
staging:
  :concurrency: 5
  :logfile: ./log/sidekiq.log
production:
  :concurrency: 5
  :logfile: ./log/sidekiq.log
development:
  :concurrency: 5
:queues:
  - default
